train: data/train/images  # 5388 images
test: data/testA/images   # 1762 images

# number of classes
nc: 7

# class names
names: [ 'background', 'edge_anomaly', 'angular_anomaly', 'white_spot_defect', 'light_block_defect',
         'dark_spot_block_defect', 'aperture_defect' ]
# names: [ '背景', '边异常', '角异常', '白色点瑕疵', '浅色块瑕疵', '深色点块瑕疵', '光圈瑕疵']
